# This file is the entry point to configure your website.
# https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/SiteHandling/Basics.html#the-configuration-file
rootPageId: 1
base: '%env(TYPO3_BASE_DOMAIN_MAIN)%'
websiteTitle: "What's Up"

languages:
    -
        title: English
        enabled: true
        languageId: 0
        base: /en/
        typo3Language: default
        locale: en_GB.UTF-8
        iso-639-1: en
        navigationTitle: English
        hreflang: en
        direction: ltr
        flag: us
    -
        title: Deutsch
        enabled: true
        languageId: 1
        base: /de/
        typo3Language: de
        locale: de_DE.UTF-8
        iso-639-1: de
        navigationTitle: Deutsch
        hreflang: de
        direction: ltr
        flag: de
        fallbackType: strict
        fallbacks: ''

errorHandling:
    -
        errorCode: 404
        errorHandler: 'PHP'
        errorPhpClassFQCN: 'App\Error\NotFound\PageErrorHandler'
        errorPageId: 1
    -
        errorCode: 403
        errorHandler: 'PHP'
        errorPhpClassFQCN: 'App\Error\AccessDenied\PageErrorHandler'
        errorPageId: 1
    -
        errorCode: 503
        errorHandler: 'PHP'
        errorPhpClassFQCN: 'App\Error\ServiceUnavailable\PageErrorHandler'
        errorPageId: 1

routes:
    -
        route: robots.txt
        type: robotsTxt
        content: ''

routeEnhancers:
    PageTypeSuffix:
        type: PageType
        default: '/'
        suffix: '/'
        index: ''
        map:
            '/': 0
            sitemap.xml: 1533906435
